name: mirror

on:
  workflow_dispatch:
    inputs:
      upstream_commit:
        description: 'Spack commit SHA'
        required: true

jobs:
  bump_develop:
    runs-on: ubuntu-20.04

    steps:
      - name: Make checkout actions setup auth
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 1
          persist-credentials: true
          ref: cscs/main
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Bump develop branch
        run: |
          git fetch https://github.com/spack/spack.git "${{ github.event.inputs.upstream_commit }}"
          git push origin "${{ github.event.inputs.upstream_commit }}:refs/heads/develop"