name: mirror

on:
  workflow_dispatch:
    inputs:
      upstream_commit:
        description: 'Spack commit SHA'
        required: true

permissions:
  contents: write

jobs:
  bump_develop:
    runs-on: ubuntu-20.04

    steps:
      - name: Make checkout actions setup auth
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: cscs/main
          fetch-depth: 1

      - name: Bump develop branch
        run: |
          git fetch https://github.com/spack/spack.git "${{ github.event.inputs.upstream_commit }}"
          git push origin "${{ github.event.inputs.upstream_commit }}:refs/heads/develop"