name: ShellCheck

on: push

jobs:
  test:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: Test
        run: shellcheck scripts/*.sh