name: ShellCheck

on: push

jobs:
  test:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
      - name: Test
        run: shellcheck scripts/*.sh