name: ShellCheck

on: push

jobs:
  test:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - name: Test
        run: shellcheck scripts/*.sh