name: ShellCheck

on: push

jobs:
  test:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - name: Test
        run: shellcheck scripts/*.sh