name: ShellCheck

on: push

jobs:
  test:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: Test
        run: shellcheck scripts/*.sh