name: ShellCheck

on: push

jobs:
  test:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - name: Test
        run: shellcheck scripts/*.sh